import { describe, it, expect } from "vitest";
import {
  calculate,
  simulate,
  defaultInputs,
  type AmortizationInputs,
} from "./amortizationEstimate";

// Characterization tests (refactor-radar RR-015): every expectation below was
// generated by executing the ORIGINAL implementation as it stood inline in
// pages/calculators/AmortizationCalculator.tsx at origin/main, before the move.
// They pin that behavior to the cent so the extraction is provably
// behavior-preserving — including the branches that are easy to break:
// acceleration via extra payments, the 0% rate path, and a partial final payment.

const extra300: AmortizationInputs = {
  loanAmount: 320000,
  interestRate: 6.5,
  loanTermYears: 30,
  extraMonthly: 300,
};

const short15: AmortizationInputs = {
  loanAmount: 450000,
  interestRate: 5.125,
  loanTermYears: 15,
  extraMonthly: 0,
};

const zeroRate: AmortizationInputs = {
  loanAmount: 240000,
  interestRate: 0,
  loanTermYears: 30,
  extraMonthly: 0,
};

const hugeExtra: AmortizationInputs = {
  loanAmount: 100000,
  interestRate: 7,
  loanTermYears: 30,
  extraMonthly: 5000,
};

describe("calculate (amortization schedule)", () => {
  it("matches the pinned output for defaultInputs — 320k / 6.5% / 30yr, no extra", () => {
    const r = calculate(defaultInputs);
    expect(r.monthlyPayment).toBeCloseTo(2022.6176751774892, 6);
    expect(r.totalInterest).toBeCloseTo(408142.3630638903, 6);
    expect(r.totalPaid).toBeCloseTo(728142.3630638903, 6);
    expect(r.payoffMonths).toBe(360);
    expect(r.baselineTotalInterest).toBeCloseTo(408142.3630638903, 6);
    expect(r.baselineMonths).toBe(360);
    expect(r.interestSaved).toBe(0);
    expect(r.monthsSaved).toBe(0);
    expect(r.yearly).toHaveLength(30);
    expect(r.monthly).toHaveLength(360);
  });

  it("pins the first and last rows of the default schedule", () => {
    const r = calculate(defaultInputs);
    expect(r.monthly[0]).toEqual({
      month: 1,
      payment: 2022.6176751774892,
      principal: 289.28434184415573,
      interest: 1733.3333333333335,
      balance: 319710.71565815585,
    });
    expect(r.monthly[359].month).toBe(360);
    expect(r.monthly[359].interest).toBeCloseTo(10.896821291851262, 6);
    expect(r.monthly[359].balance).toBe(0);
    expect(r.yearly[0]).toEqual({
      year: 1,
      principal: 3576.721500672019,
      interest: 20694.690601457853,
      balance: 320000,
      endingBalance: 316423.27849932795,
    });
    expect(r.yearly[29].year).toBe(30);
    expect(r.yearly[29].endingBalance).toBe(0);
  });

  it("matches the pinned output when an extra $300/mo accelerates payoff", () => {
    const r = calculate(extra300);
    // Base payment is unchanged by the extra; only the payoff changes.
    expect(r.monthlyPayment).toBeCloseTo(2022.6176751774892, 6);
    expect(r.totalInterest).toBeCloseTo(269696.46043795766, 6);
    expect(r.totalPaid).toBeCloseTo(589696.4604379577, 6);
    expect(r.payoffMonths).toBe(254);
    expect(r.baselineTotalInterest).toBeCloseTo(408142.3630638903, 6);
    expect(r.baselineMonths).toBe(360);
    expect(r.interestSaved).toBeCloseTo(138445.90262593265, 6);
    expect(r.monthsSaved).toBe(106);
    expect(r.yearly).toHaveLength(22);
    expect(r.monthly).toHaveLength(254);
    // The scheduled rows carry base payment + extra.
    expect(r.monthly[0].payment).toBeCloseTo(2322.617675177489, 6);
    // Final month is a partial payment, not a full one.
    expect(r.monthly[253].payment).toBeCloseTo(2074.188618052759, 6);
    expect(r.monthly[253].balance).toBe(0);
  });

  it("matches the pinned output for a 15-year term", () => {
    const r = calculate(short15);
    expect(r.monthlyPayment).toBeCloseTo(3587.9418834466337, 6);
    expect(r.totalInterest).toBeCloseTo(195829.53902037774, 6);
    expect(r.totalPaid).toBeCloseTo(645829.5390203777, 6);
    expect(r.payoffMonths).toBe(180);
    expect(r.yearly).toHaveLength(15);
    expect(r.monthly).toHaveLength(180);
    expect(r.monthly[0].interest).toBeCloseTo(1921.8749999999998, 6);
  });

  it("handles a 0% rate — straight-line principal, no interest", () => {
    const r = calculate(zeroRate);
    expect(r.monthlyPayment).toBeCloseTo(666.6666666666666, 6);
    expect(r.totalInterest).toBe(0);
    expect(r.totalPaid).toBe(240000);
    expect(r.payoffMonths).toBe(360);
    expect(r.monthly).toHaveLength(360);
    expect(r.monthly[0].interest).toBe(0);
    expect(r.monthly[0].principal).toBeCloseTo(666.6666666666666, 6);
    // Floating-point residue at payoff is pinned as-is, not rounded away.
    expect(r.monthly[359].balance).toBeCloseTo(1.2007603800157085e-9, 15);
  });

  it("matches the pinned output when the extra payment dwarfs the loan", () => {
    const r = calculate(hugeExtra);
    expect(r.monthlyPayment).toBeCloseTo(665.3024951791823, 6);
    expect(r.totalInterest).toBeCloseTo(5842.522479154953, 6);
    expect(r.payoffMonths).toBe(19);
    expect(r.baselineMonths).toBe(360);
    expect(r.monthsSaved).toBe(341);
    expect(r.interestSaved).toBeCloseTo(133666.37578535188, 6);
    expect(r.yearly).toHaveLength(2);
    expect(r.monthly).toHaveLength(19);
    expect(r.monthly[18].payment).toBeCloseTo(3867.077565929674, 6);
    expect(r.monthly[18].balance).toBe(0);
  });
});

describe("simulate (payoff loop)", () => {
  it("pins the baseline simulation for the default loan", () => {
    const r = simulate(320000, 6.5, 2022.6176751774892, 0);
    expect(r.totalInterest).toBeCloseTo(408142.3630638903, 6);
    expect(r.months).toBe(360);
  });

  it("returns Infinity when the payment never covers interest", () => {
    // 1733.33/mo of interest at month 1 — a 500/mo payment never amortizes.
    const r = simulate(320000, 6.5, 500, 0);
    expect(r.totalInterest).toBe(Infinity);
    expect(r.months).toBe(Infinity);
  });
});
