import { defineConfig } from "vitest/config";
import path from "path";

export default defineConfig({
  test: {
    globals: true,
    environment: "node",
    testTimeout: 15000,
    hookTimeout: 30000,
    // Unit / logic tests. Pure in-process logic — no running HTTP server and no
    // database required. Everything that makes network calls to the app lives in
    // vitest.integration.config.ts instead.
    include: [
      "tests/accessControl.test.ts",
      "tests/zodSchemaSemantics.test.ts",
      "tests/routeGates.test.ts",
      "tests/queryErrorHandling.test.ts",
      "tests/apiRequestConvergence.test.ts",
      "tests/queryKeyConvergence.test.ts",
      "tests/borrowerTaskView.test.ts",
      "tests/rateProductHeadings.test.ts",
      "tests/vercelDeploymentGuard.test.ts",
      "tests/loCommsLint.test.ts",
      "tests/borrowerConditionView.test.ts",
      "tests/scenarioSimulator.test.ts",
      "tests/cockpitScoping.test.ts",
      "tests/signalEngine.test.ts",
      "tests/adversarialPersonas.test.ts",
      "tests/adverseActionNotice.test.ts",
      "tests/adverseActionDelivery.test.ts",
      "tests/adverseActionPdf.test.ts",
      "tests/apr.test.ts",
      "tests/aprValidation.test.ts",
      "tests/structureTranslation.test.ts",
      "tests/encryptionRotation.test.ts",
      "tests/fairLendingAnalysis.test.ts",
      "tests/trid.test.ts",
      "tests/lookupResolver.test.ts",
      "tests/mismoValidation.test.ts",
      "tests/preApprovalMachine.test.ts",
      "tests/letterIntegrity.test.ts",
      "tests/preUnderwriting.test.ts",
      "tests/lifecycleEngine.test.ts",
      "tests/underwritingNuance.test.ts",
      "tests/incomeOrchestrator.test.ts",
      "tests/incomeCutoverParity.test.ts",
      "tests/nonQmProgramGate.test.ts",
      "tests/halalLaneGate.test.ts",
      "tests/accuracyLoop.test.ts",
      "tests/underwritingEdgeCases.test.ts",
      "tests/selfEmploymentIncome.test.ts",
      "tests/complianceInvariants.test.ts",
      "tests/scenarioCatalog.test.ts",
      "tests/statusVocabulary.test.ts",
      "tests/borrowerJourney.test.ts",
      "tests/routeGateDrift.test.ts",
      "tests/intakeSchema.test.ts",
      "tests/illinoisDpaSeed.test.ts",
      "tests/stageRequirements.test.ts",
      "tests/fileHealth.test.ts",
      "tests/borrowerStateMachine.test.ts",
      "tests/ssnVault.test.ts",
      "tests/loginLockout.test.ts",
      "tests/socialAuthProviders.test.ts",
      "tests/marketDataParsers.test.ts",
      "tests/valueEstimate.test.ts",
      "tests/propertyEligibility.test.ts",
      "tests/errorMessage.test.ts",
      "tests/mismoMersMin.test.ts",
      "tests/mismoExport.test.ts",
      "tests/quietHours.test.ts",
      "tests/mcpAudit.test.ts",
      "tests/mcpAgentIdentity.test.ts",
      "tests/smsCompliance.test.ts",
      "tests/errorMonitoring.test.ts",
      "tests/auditReanchor.test.ts",
      "tests/qmThresholds.test.ts",
      "tests/specialFeatureCodes.test.ts",
      "tests/loanDeliveryEdits.test.ts",
      "tests/brokerSubmissionReadiness.test.ts",
      "tests/incomeAnalysisPackage.test.ts",
      "tests/lenderSubmission.test.ts",
      "tests/pipelineEngineDocumentRequirements.test.ts",
      "tests/leadNotifications.test.ts",
      "tests/uploadsPresignedOnly.test.ts",
      "tests/rateLimitRelaxed.test.ts",
      "tests/betaGate.test.ts",
      "tests/prelaunchGate.test.ts",
      "tests/taxInsight.test.ts",
      "tests/extractionService.test.ts",
      "tests/taxDocumentIntelligence.test.ts",
      "tests/taxReconciliation.test.ts",
      "tests/situationClassifier.test.ts",
      "tests/documentConfidence.test.ts",
      "tests/documentReview.test.ts",
      "tests/cpaPartners.test.ts",
      "tests/partnerProfiles.test.ts",
      "tests/mismoXsdValidation.test.ts",
      "tests/approvalStrength.test.ts",
      "tests/buyingPowerEstimate.test.ts",
      "tests/loanScenarioMatrix.test.ts",
      "tests/documentTypeAliases.test.ts",
      "tests/localObjectStorage.test.ts",
      "tests/postAuthRoute.test.ts",
      "tests/borrowerOfferView.test.ts",
      "tests/queryParams.test.ts",
      "tests/vercelEntryHelpers.test.ts",
      "tests/spaCatchAll.test.ts",
      "tests/coachProfileSync.test.ts",
      "tests/coachTools.test.ts",
      "tests/coachLintFilter.test.ts",
      "tests/coachSse.test.ts",
      "tests/autopilotFollowUps.test.ts",
      "tests/autopilotAusFollowUps.test.ts",
      "tests/autopilotDecisionRelay.test.ts",
      "tests/autopilotConsole.test.ts",
      "tests/riskBrief.test.ts",
      "tests/sensitiveInputGuard.test.ts",
      "tests/licensedStates.test.ts",
      "tests/documentStatus.test.ts",
      "tests/documentReviewNotifications.test.ts",
      "tests/documentConditionRevert.test.ts",
      "tests/documentTaskOwnerRole.test.ts",
      "tests/taskCancellation.test.ts",
      "tests/taskEngineSlaSeed.test.ts",
      "tests/uploadValidation.test.ts",
      "tests/documentChecklist.test.ts",
      "tests/complianceScore.test.ts",
    ],
    // Some modules under test transitively import server/db.ts, which refuses to
    // boot without a DATABASE_URL. Unit tests never touch the database, so a
    // placeholder keeps them hermetic (no .env or real database needed).
    env: {
      DATABASE_URL:
        process.env.DATABASE_URL ??
        "postgresql://unit-tests:placeholder@localhost:5432/unit_tests_never_connects",
    },
  },
  resolve: {
    alias: {
      "@shared": path.resolve(__dirname, "shared"),
      "@": path.resolve(__dirname, "client", "src"),
    },
  },
});
