import { describe, expect, it } from "vitest";
import {
  toBorrowerConditionView,
  toBorrowerConditionViews,
  type MaskableLoanCondition,
} from "@shared/borrowerConditionView";

/**
 * Borrower Clarity PR 5 (kb log 2026-08-04 §4): the pipeline/conditions
 * payloads are a strict whitelist for non-staff callers. Field-absence pinned
 * in the borrowerOfferView style so a future edit can't quietly re-expose
 * staff clearance notes or the wholesale-lender linkage.
 */

const condition = (over: Partial<MaskableLoanCondition> = {}): MaskableLoanCondition => ({
  id: "c-1",
  applicationId: "app-1",
  category: "income",
  title: "Year-to-date P&L",
  description: "Provide a YTD profit-and-loss statement for the business.",
  priority: "prior_to_docs",
  status: "outstanding",
  requiredDocumentTypes: ["profit_loss_statement"],
  clearedAt: null,
  createdAt: "2026-08-01T00:00:00.000Z",
  updatedAt: null,
  ...over,
});

/** The raw row a careless refactor might spread into the response. */
const rawRowHazards = {
  clearanceNotes: "internal: cleared per UW override after second-look",
  clearedByUserId: "staff-user-42",
  sourceRule: "rule-se-income-docs",
  linkedTaskId: "task-internal-7",
  lenderSubmissionId: "sub-angel-oak-1",
  isAutoGenerated: true,
};

describe("toBorrowerConditionView — whitelist", () => {
  it("keeps the borrower-facing fields", () => {
    const view = toBorrowerConditionView(condition());
    expect(view.title).toBe("Year-to-date P&L");
    expect(view.description).toContain("profit-and-loss");
    expect(view.category).toBe("income");
    expect(view.priority).toBe("prior_to_docs");
    expect(view.status).toBe("outstanding");
    expect(view.requiredDocumentTypes).toEqual(["profit_loss_statement"]);
    expect(view.createdAt).toBe("2026-08-01T00:00:00.000Z");
  });

  it("never emits clearance notes, staff ids, rule/task linkage, or the lender-submission link", () => {
    const view = toBorrowerConditionView({
      ...condition(),
      ...(rawRowHazards as Partial<MaskableLoanCondition>),
    });
    const serialized = JSON.stringify(view);
    for (const [key, value] of Object.entries(rawRowHazards)) {
      if (typeof value === "string") {
        expect(serialized, `field ${key} leaked`).not.toContain(value);
      }
      expect(key in view, `key ${key} present`).toBe(false);
    }
  });

  it("scrubs wholesale-lender identity out of transcribed condition text", () => {
    const view = toBorrowerConditionView(
      condition({
        title: "Angel Oak Mortgage Solutions: 12 months business bank statements",
        description: "Newrez Wholesale requires the most recent two statements.",
      }),
    );
    expect(view.title).not.toContain("Angel Oak");
    expect(view.title).toContain("Lender");
    expect(view.description).not.toContain("Newrez");
    expect(view.description).toContain("Lender requires");
  });

  it("maps arrays and defaults requiredDocumentTypes to empty", () => {
    const views = toBorrowerConditionViews([condition({ requiredDocumentTypes: null })]);
    expect(views[0].requiredDocumentTypes).toEqual([]);
  });

  it("scrubs the industry shorthand staff actually type (§9 F-1 probe cases)", () => {
    // "Angel Oak" (no legal suffix), "Rocket Pro" (no TPO), "United Wholesale"
    // (no Mortgage), and the space-joined id form all bypassed the original
    // name+id vocabulary — pinned here so the alias derivation can't regress.
    const cases: Array<[string, string]> = [
      ["Angel Oak: provide 12 months business bank statements", "Angel Oak"],
      ["Rocket Pro needs updated VOE", "Rocket Pro"],
      ["United Wholesale needs appraisal recert", "United Wholesale"],
      ["angel oak condition follow-up", "angel oak"],
      ["rocket pro tpo overlay applies", "rocket pro tpo"],
    ];
    for (const [title, leak] of cases) {
      const view = toBorrowerConditionView(condition({ title }));
      expect(view.title.toLowerCase(), title).not.toContain(leak.toLowerCase());
      expect(view.title, title).toContain("Lender");
    }
  });
});
