-- 0031: require document_confidence_scores.extraction_engine to name its engine.
-- Completes 0030. That migration dropped the stale 'gemini' default so an omitting
-- writer could no longer be stamped with a retired engine — but the column stayed
-- NULLABLE, so the same writer would record NULL ("engine unrecorded") instead of
-- erroring. A gap is honest where a wrong value is not, but neither belongs in an
-- AI-provenance column: NOT NULL makes the engine a required field, so TypeScript
-- rejects a future insert path that omits it (the DB is the backstop, the compiler
-- is the actual gate).
--
-- CONTRACT step, not additive — SET NOT NULL fails outright if any row is NULL, and
-- a failure here fails the post-merge migrate-prod job (the 2026-07-13 outage class).
-- Pre-flight run against PROD before authoring (read-only probe, CI run 29553889961,
-- 2026-07-17), which reported:
--     column shape — is_nullable=YES default=(none) maxlen=30   [0030 confirmed applied]
--     rows total=0 nulls=0
-- Zero rows, so this ALTER cannot fail on data, and no backfill is needed or wanted —
-- a guessed engine would falsify the audit trail this column exists to keep. (Note
-- `migrate-prod.cjs --dry-run` could NOT have answered this: it only lists pending
-- migrations and never executes their SQL.)
--
-- Backward-compatible in both directions, so it is safe to land with the schema change:
-- the deployed app has set this column on every insert since #146 — the sole writer,
-- recordExtractionConfidence() in server/services/documentConfidence.ts, does
-- `options.extractionEngine || "claude"` — so the running code tolerates the tightened
-- DB, and the new code tolerates a not-yet-migrated one. No rows are rewritten, so
-- historical 'gemini' rows keep their legitimate provenance. Idempotent: SET NOT NULL
-- on an already-NOT NULL column is a silent no-op, so a re-run is safe.
ALTER TABLE "document_confidence_scores"
	ALTER COLUMN "extraction_engine" SET NOT NULL;
