-- 0046: one row per (profile_id, version) in policy_profiles
--
-- shared/schema/underwritingPolicy.ts comments version as "CRITICAL for legal
-- compliance" and policy_profiles carries a full DRAFT -> PENDING_APPROVAL ->
-- APPROVED -> ACTIVE -> RETIRED lifecycle with approver and activator columns.
-- A versioned, approved artefact whose (identifier, version) pair can repeat
-- is not versioned: two rows could both claim to be FNMA_CONVENTIONAL_2026_Q3
-- v1.1.0 with different thresholds, and nothing would say which one an
-- approval or an activation referred to.
--
-- Nothing prevents that today. The only indexes on the table are the four
-- non-unique ones in the schema (authority, product_type, status,
-- effective_date); no migration has ever added a unique constraint here.
--
-- The clone endpoint added alongside this migration depends on it: it derives
-- a new version by bumping the highest one in use for that profile_id, and the
-- index is what makes that derivation a guarantee rather than a convention.
--
-- CONTRACT MIGRATION — DB_MIGRATIONS.md §Contract migrations.
-- A unique index aborts if duplicates already exist, so the assumption has to
-- be stated. What was verified in the repository:
--   * policy_profiles has no seed data. Searched migrations/, scripts/ and
--     server/ for inserts or fixtures against the table: none exist.
--   * exactly one code path creates a row — storage.createPolicyProfile,
--     called only from POST /api/policy-profiles.
--   * that endpoint's only UI trigger was the "Create Policy Draft" button,
--     which had no click handler at all until this same change set. It could
--     not have been called from the app.
-- Therefore the expected production count is 0 rows and 0 duplicate pairs.
--
-- VERIFIED AGAINST PROD — read-only probe, CI run 31067324031 (2026-08-06),
-- branch probe/0046-policy-profile-duplicates (deleted after the run, per
-- DB_MIGRATIONS.md §Contract migrations). The probe replaced the migrate-prod
-- apply step rather than adding to it, so no dispatch input could reach a
-- write. What it reported:
--
--   policy_profiles present            : true
--   total_rows                         : 0
--   distinct (profile_id, version)     : 0
--   rows with NULL profile_id          : 0
--   rows with NULL version             : 0
--   duplicate (profile_id, version)    : 0
--   idx_policy_profiles_id_version     : not present
--   existing indexes                   : idx_policy_profiles_authority,
--                                        idx_policy_profiles_effective,
--                                        idx_policy_profiles_product,
--                                        idx_policy_profiles_status,
--                                        policy_profiles_pkey
--
-- Prod holds the four non-unique indexes the schema declares and nothing else,
-- exactly as the repository evidence above predicted, and the table is empty.
-- CREATE UNIQUE INDEX has nothing to abort on. Probe query, verbatim:
--   SELECT profile_id, version, COUNT(*) FROM policy_profiles
--   GROUP BY profile_id, version HAVING COUNT(*) > 1;
-- Returned 0 rows.
--
-- The zero count is what licenses this migration; it is not a promise about
-- the future. If rows are created between this probe and the merge, the
-- migration fails loudly in migrate-prod rather than silently permitting
-- duplicate versions — which is the correct failure for this constraint.

CREATE UNIQUE INDEX IF NOT EXISTS idx_policy_profiles_id_version
  ON policy_profiles (profile_id, version);
