-- F-046: version the audit entry hash so sequence numbers become forgery-proof.
--
-- The v1 hash covered an entry's content and its backpointer but NOT its
-- sequence_number, so an attacker who deleted rows could renumber the survivors
-- and defeat the contiguity check added by F-038. v2 folds sequence_number AND
-- the version marker itself into the digest; including the marker is what makes
-- a downgrade fail, since verifying a v2 row as v1 omits two fields and produces
-- a different hash.
--
-- EXPAND ONLY. Adds one nullable column; no existing row is read or written, and
-- no constraint is applied to existing data, so there is no contract-migration
-- data check to record. The deployed app tolerates the new column and the new
-- app tolerates rows without it.
--
-- DELIBERATELY NOT BACKFILLED, and this one is not a close call. Writing
-- hash_version = 1 onto existing rows would be harmless in itself, but writing
-- hash_version = 2 (or re-hashing them to v2) would mean rewriting historical
-- audit entries so that they verify -- precisely the act an audit log exists to
-- make impossible. NULL reads as v1 and is the honest statement that an entry
-- predates the scheme. Old entries stay renumberable; verification reports that
-- as coverage.sequenceIntegrity = 'unhashed' or 'mixed' rather than implying a
-- protection that is not there.
ALTER TABLE "credit_audit_log" ADD COLUMN IF NOT EXISTS "hash_version" integer;--> statement-breakpoint
COMMENT ON COLUMN "credit_audit_log"."hash_version" IS 'Hash algorithm for entry_hash (F-046). NULL = v1 (pre-versioning; does not hash sequence_number, so those rows are renumberable). 2 = sequence_number and this marker are inside the digest. Never backfilled.';
